language: node_js
node_js:
    - "10"

install:
  - cd client
  - npm install
  - cd ../server
  - npm install

services:
  - mongodb

script:
  - cd ../client
  - npm run test
  - npm run build
  - cd ../server
  - npm run build
  - npm run test

notifications:
  email: false

cache:
  directories:
    - client/node_modules
    - server/node_modules

env:
  - MONGODB_URL=mongodb://localhost:27017/musicmap HTTP_SERVER_PORT=4000 HTTPS_SERVER_PORT=4001 SERVER_KEY_PATH=<you-can-leave-it-blank> SERVER_CRT_PATH=<you-can-leave-it-blank> CA_CRT_PATH=<you-can-leave-it-blank> SPOTIFY_CLIENT_ID=someclientid SPOTIFY_CLIENT_SECRET=somesecret SPOTIFY_TOKEN_URL=https://accounts.spotify.com/api/token SPOTIFY_WEB_API_BASE_URL=https://api.spotify.com/v1
