language: node_js
node_js: node

install:
  - cd client
  - npm install
  - cd ../server
  - npm install

script:
  - cd ../client
  - npm run test
  - npm run build
  - cd ../server
  - npm run test
  - npm run build

notifications:
  email: false

cache:
  directories:
    - client/node_modules
    - server/node_modules

env:
  - MONGODB_URL=mongodb://localhost:27017/musicmap
