export const PLAYER = {
  PREVIOUS_TRACK : 'PREVIOUS_TRACK',
  NEXT_TRACK : 'NEXT_TRACK',
  SHUFFLE_TRACKS : 'SHUFFLE_TRACKS',
  LOOP_SAME_TRACK : 'LOOP_SAME_TRACK',
  LOOP_ALL_TRACKS : 'LOOP_ALL_TRACKS',
  CURRENT_TRACK : 'CURRENT_TRACK',
  CHANGE_PLAYER_TYPE: 'CHANGE_PLAYER_TYPE',
  STORE_ALL_TRACKS: 'STORE_ALL_TRACKS',
  UPDATE_CURRENT_DEVICE_ID: 'UPDATE_CURRENT_DEVICE_ID',
  UPDATE_PLAYER_STATE: 'UPDATE_PLAYER_STATE',
};

export const SPOTIFY = {
  GET_ACCESS_TOKEN : 'GET_ACCESS_TOKEN',
  GET_TRACK_DETAILS : 'GET_TRACK_DETAILS'
}

export const AUTH = {
  SET_CURRENT_USER : 'SET_CURRENT_USER'
}
